### ISSUE TITLE
Installing this extension brings big test folder

### ISSUE THREAD

**Issue by JiaChen-Zeng** [SoftwareApe/NumberMonger#1]
The installation takes several minutes, so I have a look at the extension folder and find that 180M big folder. I try to uninstall and reinstall again. Still brings me the folder.

![default](https://user-images.githubusercontent.com/3676278/33793359-a2ffebc8-dcf1-11e7-8c1f-66b18ac4d6a0.png)

By the way, there is only `VSCode-linux-x64` in this folder.

**Comment by SoftwareApe** [comment]
I'll have to check it out, it indeed seems to install a bit too much. I'm working on Linux, so probably the VSCode extension publisher picked something up generated for testing on my machine which shouldn't be there. Thank you for pointing it out!

**Comment by SoftwareApe** [comment]
HI, Issue is resolved with release 0.1.3! The complete folder is now ~836KB.
