### ISSUE TITLE
Not working with floats

### ISSUE THREAD

**Issue by arturcarvalho** [SoftwareApe/NumberMonger#2]
I'm using this tool to quickly add up some numbers, it's been very helpful, thank you!

But I can't use floats.  For instance, if I add this up:
1
.1
0.1

I get the result 3. Shouldn't it be 1.2? Maybe this is more of a feature request than an issue.

Thanks in advance and thanks for the extension.

**Comment by SoftwareApe** [comment]
Hi Artur,

thank you for the feedback! I should have maybe made it more clear that it's not made to work with floats. I might add this feature, but I'm currently quite busy with work.

**Comment by arturcarvalho** [comment]
Hi @SoftwareApe. No problem, thanks anyway! I'm going to take a look at how to develop an extension and maybe do the change myself.

**Comment by SoftwareApe** [comment]
I added the feature in the most recent commit. You can reopen this issue if you like. Try it out, if you have any suggestions, tell me. I haven't made a new release yet on marketplace, but I'm going to.

**Comment by SoftwareApe** [comment]
You can now upgrade to version 0.2.0.

**Comment by arturcarvalho** [comment]
Thank you!
