### ISSUE TITLE
Median bug

### ISSUE THREAD

**Issue by lubrogit** [SoftwareApe/NumberMonger#3]
Sequence "1  2  3  4  5  6  7  8  9  10  11  12  13" gives "median = 3".
Otherwise very good extension.
A wish: Insert floating sequence

**Comment by SoftwareApe** [comment]
Good catch, I'll have to check and see if I can reproduce this later.

I can't promise to get on it too early, but I'll try my best.

**Comment by SoftwareApe** [comment]
Bug is fixed in 0.2.1

**Comment by SoftwareApe** [comment]
I'm closing the issue. I posted "insert floating sequence" as a separate enhancement issue.

**Comment by SoftwareApe** [comment]
I'm closing the issue, I filed a separate enhancement issue for "insert floating sequence".

**Comment by SoftwareApe** [comment]
The enhancement issue #4 is closed.

**Comment by lubrogit** [comment]
Insert (Float) works well, e.g.
1  1.1  1.2  1.3  1.4  1.5  1.6  1.7000000000000002  1.8  1.9  2  2.1  2.2  2.3  2.4000000000000004  2.5  2.6  2.7  2.8  2.9000000000000004  3  3.1  3.2  3.3000000000000003  3.4000000000000004
Nevertheless, formatting derived from the entered step value format would be welcomed.

**Comment by SoftwareApe** [comment]
I thought about this, too, however the formatting would somehow need to
depend on start and step value. I didn't have a nice solution so I left it
at this for now.

You could have start of 0.1 and step of 1, then step based formatting would
break.

lubrogit <notifications@github.com> schrieb am Fr., 9. Nov. 2018, 16:46:

**Comment by lubrogit** [comment]
I would think of using the formatting of the step value, in the suggested case the step should be "1.0". That means to parse the step value string and decide.
