### ISSUE TITLE
why change file's EOL after insert?

### ISSUE THREAD

**Issue by zheung** [SoftwareApe/NumberMonger#6]
My file's EOL is `CRLF` now.
After insert some sequences, my file's EOL was changed to `LF`.

is it BUG?

**Comment by SoftwareApe** [comment]
Hi, did you close because it a wasn't an issue or why? I'm working on Linux, so this might be an issue I didn't notice yet.

**Comment by zheung** [comment]
Sorry, I should test more before open a issue.
I found that it is not `NumberMonger`'s problem.
Other extensions have same problem on Windows and Code insider too.

**Comment by SoftwareApe** [comment]
没问题！
