### ISSUE TITLE
copy result to clipboard

### ISSUE THREAD

**Issue by forgi007** [SoftwareApe/NumberMonger#7]
Great extension! It would be even better if I could copy the mean,sum, etc. values to clipboard somehow.

**Comment by forgi007** [comment]
Sorry, this should be a comment or ask for feature... I just do not know how to do that.

**Comment by SoftwareApe** [comment]
Issues can also be feature requests. That's not wrong, I'm not sure whether I can write these values to clipboard, maybe I check it out at some point.

**Comment by SoftwareApe** [comment]
New feature available in 0.5.0

**Comment by forgi007** [comment]
Works :) great, thanks a lot!

Tamas

Carl <notifications@github.com> ezt írta (időpont: 2019. máj. 24., P,
17:29):
